# Generated by Django 4.1.2 on 2022-12-02 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=40)),
                ("numberPlate", models.CharField(max_length=30)),
                ("mainOffices", models.CharField(max_length=30)),
                ("travelTime", models.TimeField()),
                ("seats", models.IntegerField()),
                ("status", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="BusCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("companyName", models.CharField(max_length=30)),
                ("region", models.CharField(max_length=30)),
                ("shiftsTo", models.IntegerField()),
                ("shiftsFrom", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tickets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticketNo", models.CharField(max_length=2, unique=True)),
                ("toPlace", models.CharField(max_length=20)),
                ("fromPlace", models.CharField(max_length=20)),
                ("ticketShift", models.DateTimeField()),
                ("busToBeUsed", models.CharField(max_length=20)),
                (
                    "busToBeUsedNumberPlate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="transportug.bus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                ("busCompany", models.CharField(max_length=30)),
                ("setOffTime", models.CharField(max_length=30)),
                (
                    "startLocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="transportug.buscompany",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bus",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="regions",
                to="transportug.buscompany",
            ),
        ),
        migrations.CreateModel(
            name="BookedCustomers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shiftBooked", models.DateTimeField()),
                ("bookingDate", models.DateTimeField()),
                (
                    "busBooked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="busBooked",
                        to="transportug.bus",
                    ),
                ),
                (
                    "busNumberPlate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="numberPlates",
                        to="transportug.bus",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticketNumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ticketNos",
                        to="transportug.tickets",
                    ),
                ),
            ],
        ),
    ]
