# Generated by Django 4.1.2 on 2022-12-08 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("companyName", models.CharField(max_length=30)),
                ("region", models.CharField(max_length=30)),
                ("shiftsTo", models.IntegerField()),
                ("shiftsFrom", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Prices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                ("busCompany", models.CharField(max_length=30)),
                ("setOffTime", models.CharField(max_length=30)),
                (
                    "startLocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="transportug.buscompany",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=40)),
                ("numberPlate", models.CharField(max_length=30)),
                ("mainOffices", models.CharField(max_length=30)),
                ("travelTime", models.TimeField()),
                ("seats", models.IntegerField()),
                ("totalTickets", models.CharField(default=64, max_length=2)),
                ("status", models.CharField(max_length=30)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="regions",
                        to="transportug.buscompany",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookedCustomers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("busBooked", models.CharField(max_length=30, null=True)),
                ("ticketNumber", models.CharField(max_length=30, null=True)),
                ("busNumberPlate", models.CharField(max_length=30, null=True)),
                ("bookingDate", models.DateTimeField(null=True)),
                ("seatNumber", models.CharField(max_length=6, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transportug.bus",
                    ),
                ),
            ],
        ),
    ]
