# Generated by Django 4.1.2 on 2022-12-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transportug", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickets",
            name="ticketNo",
        ),
        migrations.AddField(
            model_name="bookedcustomers",
            name="seatNumber",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="tickets",
            name="totalTickets",
            field=models.CharField(default=64, max_length=2),
        ),
    ]
