# Generated by Django 4.1.2 on 2022-10-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportug', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buscompany',
            name='busImage',
        ),
        migrations.AddField(
            model_name='bus',
            name='busImage',
            field=models.ImageField(null=True, upload_to='buses'),
        ),
    ]
