# Generated by Django 4.1.2 on 2022-12-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transportug", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="price",
            field=models.IntegerField(null=True),
        ),
    ]
