# Generated by Django 4.1.2 on 2022-12-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "transportug",
            "0002_remove_tickets_ticketno_bookedcustomers_seatnumber_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="totalTickets",
            field=models.CharField(default=64, max_length=2),
        ),
        migrations.AlterField(
            model_name="bookedcustomers",
            name="ticketNumber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ticketNos",
                to="transportug.bus",
            ),
        ),
        migrations.DeleteModel(
            name="Tickets",
        ),
    ]
