# Generated by Django 4.1.2 on 2022-10-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportug', '0003_remove_bus_busimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='company',
            field=models.CharField(max_length=40),
        ),
    ]
