# Generated by Django 4.1.2 on 2022-12-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transportug",
            "0003_bus_totaltickets_alter_bookedcustomers_ticketnumber_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedcustomers",
            name="bookingDate",
            field=models.DateTimeField(null=True),
        ),
    ]
