# Generated by Django 4.1.2 on 2022-12-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transportug", "0005_alter_bookedcustomers_shiftbooked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedcustomers",
            name="seatNumber",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
